SELECT_ALL_FUNCIONARIOS = "SELECT * FROM funcionarios"
SELECT_NOME_CARRO_OCUP = "SELECT nome_carro, ocup FROM carros"
SELECT_FUNCIONARIOS_DETALHADOS = "SELECT nome_funcio, cargo_funcio, login_funcio, senha_funcio FROM funcionarios"
SELECT_CLIENTES = "SELECT nome_cliente, cnh_cliente, nasc_cliente, end_cliente, tel_cliente FROM cliente"
INSERT_FUNCIONARIO = "INSERT INTO funcionarios(nome_funcio, login_funcio, cargo_funcio, senha_funcio) VALUES (?, ?, ?, ?)"
INSERT_CLIENTE = "INSERT INTO cliente(nome_cliente, cnh_cliente, nasc_cliente, end_cliente, tel_cliente) VALUES (?, ?, ?, ?, ?)"
UPDATE_CLIENTE = "UPDATE cliente SET nome_cliente=?, cnh_cliente=?, nasc_cliente=?, end_cliente=?, tel_cliente=? WHERE nome_cliente=? AND cnh_cliente=? AND end_cliente=? AND tel_cliente=?"
UPDATE_FUNCIONARIO = "UPDATE funcionarios SET nome_funcio=?, login_funcio=?, cargo_funcio=?, senha_funcio=? WHERE nome_funcio=? AND login_funcio=? AND cargo_funcio=? AND senha_funcio=?"
DELETE_FUNCIONARIO = "DELETE FROM funcionarios WHERE nome_funcio=? AND cargo_funcio=? AND login_funcio=? AND senha_funcio=?"
DELETE_CLIENTE = "DELETE FROM cliente WHERE nome_cliente=? AND cnh_cliente=?"
UPDATE_CARRO = "UPDATE carros SET cliente=?, data_alug=?, data_dev=?, ocup=? WHERE nome_carro=?"
UPDATE_OCUPACAO_CARRO = "UPDATE carros SET ocup=? WHERE nome_carro=?"